import React, { useState } from 'react';
import { HelpCircle, CheckCircle, XCircle, Sparkles, RefreshCw, Trophy, ArrowRight } from 'lucide-react';
import confetti from 'canvas-confetti';
import { fetchQuiz } from '../services/api';

export default function QuizGenerator({ activeSubject }) {
  const [quiz, setQuiz] = useState(null);
  const [selectedOption, setSelectedOption] = useState(null);
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [score, setScore] = useState(0);
  const [totalAttempts, setTotalAttempts] = useState(0);

  const handleGenerateQuiz = async () => {
    setIsLoading(true);
    setSelectedOption(null);
    setIsSubmitted(false);

    try {
      const data = await fetchQuiz();
      setQuiz(data);
    } catch (err) {
      console.error(err);
    } finally {
      setIsLoading(false);
    }
  };

  const handleOptionSelect = (idx) => {
    if (isSubmitted) return;
    setSelectedOption(idx);
  };

  const handleCheckAnswer = () => {
    if (selectedOption === null || isSubmitted) return;
    setIsSubmitted(true);
    setTotalAttempts(prev => prev + 1);

    if (selectedOption === quiz.correct) {
      setScore(prev => prev + 1);
      // Trigger victory confetti
      confetti({
        particleCount: 70,
        spread: 60,
        origin: { y: 0.7 }
      });
    }
  };

  return (
    <div className="glass-panel" style={{
      margin: '24px var(--pad-page) 0 var(--pad-page)',
      padding: '28px',
      display: 'flex',
      flexDirection: 'column',
      gap: '20px'
    }}>
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '12px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          <div style={{
            width: '36px',
            height: '36px',
            borderRadius: '10px',
            background: 'rgba(193, 255, 0, 0.15)',
            border: '1px solid rgba(193, 255, 0, 0.3)',
            display: 'grid',
            placeItems: 'center',
            color: 'var(--neon-lime)'
          }}>
            <HelpCircle size={20} />
          </div>

          <div>
            <h3 style={{ fontSize: '1.1rem', fontWeight: 600 }}>Sessional Quiz Engine</h3>
            <p style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>
              Autogenerated multiple-choice questions derived directly from your notes' vector space.
            </p>
          </div>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          <div className="glass-panel" style={{ padding: '6px 14px', borderRadius: 'var(--radius-pill)', display: 'flex', alignItems: 'center', gap: '6px' }}>
            <Trophy size={14} color="var(--neon-lime)" />
            <span className="mono-text" style={{ fontSize: '0.78rem' }}>
              Score: <strong style={{ color: 'var(--neon-lime)' }}>{score}</strong> / {totalAttempts}
            </span>
          </div>

          <button
            onClick={handleGenerateQuiz}
            disabled={isLoading}
            className="btn-primary"
            style={{ padding: '8px 16px', fontSize: '0.82rem' }}
          >
            <RefreshCw size={14} className={isLoading ? 'pulse-dot' : ''} />
            <span>{isLoading ? 'Extracting Vector Concepts...' : 'Generate New Question'}</span>
          </button>
        </div>
      </div>

      {/* Quiz Card Body */}
      {!quiz ? (
        <div style={{
          padding: '48px 24px',
          textAlign: 'center',
          background: 'rgba(0,0,0,0.2)',
          borderRadius: 'var(--radius-lg)',
          border: '1px dashed rgba(255,255,255,0.15)'
        }}>
          <Sparkles size={32} color="var(--neon-cyan)" style={{ margin: '0 auto 12px auto' }} />
          <h4 style={{ fontSize: '1.05rem', fontWeight: 600 }}>Ready to Test Your Knowledge?</h4>
          <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginTop: '4px', marginBottom: '16px' }}>
            Click "Generate New Question" to extract concepts from your active vector library.
          </p>
          <button onClick={handleGenerateQuiz} className="btn-primary">
            Generate Quiz Question
          </button>
        </div>
      ) : (
        <div style={{
          background: 'rgba(255, 255, 255, 0.03)',
          border: '1px solid rgba(255, 255, 255, 0.08)',
          borderRadius: 'var(--radius-lg)',
          padding: '24px',
          display: 'flex',
          flexDirection: 'column',
          gap: '20px'
        }}>
          <div style={{ fontSize: '1.05rem', fontWeight: 600, lineHeight: 1.4 }}>
            {quiz.question}
          </div>

          {/* Options Grid */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
            {quiz.options.map((opt, idx) => {
              const isSelected = selectedOption === idx;
              const isCorrect = idx === quiz.correct;

              let btnBg = 'rgba(255,255,255,0.04)';
              let borderCol = 'rgba(255,255,255,0.12)';
              let textColor = 'var(--text-main)';

              if (isSubmitted) {
                if (isCorrect) {
                  btnBg = 'rgba(193, 255, 0, 0.15)';
                  borderCol = 'var(--neon-lime)';
                  textColor = 'var(--neon-lime)';
                } else if (isSelected && !isCorrect) {
                  btnBg = 'rgba(255, 76, 65, 0.15)';
                  borderCol = 'var(--alert-red)';
                  textColor = 'var(--alert-red)';
                }
              } else if (isSelected) {
                btnBg = 'rgba(51, 70, 255, 0.2)';
                borderCol = 'var(--brand-blue)';
              }

              return (
                <button
                  key={idx}
                  onClick={() => handleOptionSelect(idx)}
                  disabled={isSubmitted}
                  style={{
                    padding: '14px 18px',
                    borderRadius: '12px',
                    background: btnBg,
                    border: `1px solid ${borderCol}`,
                    color: textColor,
                    fontSize: '0.9rem',
                    textAlign: 'left',
                    cursor: isSubmitted ? 'default' : 'pointer',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'space-between',
                    transition: 'all 0.2s var(--ease-smooth)'
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                    <span className="mono-text" style={{
                      width: '24px',
                      height: '24px',
                      borderRadius: '50%',
                      background: 'rgba(255,255,255,0.08)',
                      display: 'grid',
                      placeItems: 'center',
                      fontSize: '0.75rem'
                    }}>
                      {String.fromCharCode(65 + idx)}
                    </span>
                    <span>{opt}</span>
                  </div>

                  {isSubmitted && isCorrect && <CheckCircle size={18} color="var(--neon-lime)" />}
                  {isSubmitted && isSelected && !isCorrect && <XCircle size={18} color="var(--alert-red)" />}
                </button>
              );
            })}
          </div>

          {/* Action & Explanation Footer */}
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '12px', marginTop: '10px' }}>
            {!isSubmitted ? (
              <button
                onClick={handleCheckAnswer}
                disabled={selectedOption === null}
                className="btn-primary"
              >
                <span>Submit Answer</span>
                <ArrowRight size={16} />
              </button>
            ) : (
              <button onClick={handleGenerateQuiz} className="btn-primary">
                <span>Next Question</span>
                <RefreshCw size={16} />
              </button>
            )}

            {isSubmitted && quiz.explanation && (
              <div style={{
                flex: 1,
                padding: '12px 16px',
                borderRadius: '10px',
                background: selectedOption === quiz.correct ? 'rgba(193, 255, 0, 0.08)' : 'rgba(255, 76, 65, 0.08)',
                border: '1px solid ' + (selectedOption === quiz.correct ? 'rgba(193, 255, 0, 0.3)' : 'rgba(255, 76, 65, 0.3)'),
                fontSize: '0.82rem',
                color: 'var(--text-main)',
                lineHeight: 1.4
              }}>
                <strong>Explanation:</strong> {quiz.explanation}
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
